handlebars:
  suffix: .html
  cache: false
  
spring:  datasource:    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: VANITYFAIRSTANDARD
    password: VANITYFAIR!STANDARD  jpa:    hibernate:      ddl-auto: none    show-sql: true  devtools:    livereload:      enabled: true
